version: '3.8'

services:
  mysql8.0:
    image: mysql:8.0
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 'root'
    restart: 'always'
    container_name: mysql8.0
    volumes:
      - '/home/docker-data/mysql8.0:/var/lib/mysql'
      - './conf:/etc/mysql/conf.d'

  mysql5.7:
    image: mysql:5.7
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 'root'
    restart: 'always'
    container_name: mysql5.7
    volumes:
      - '/home/docker-data/mysql5.7:/var/lib/mysql'
      - './conf:/etc/mysql/conf.d'
