version: '3.7'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    restart: 'always'
    container_name: mysql
    volumes:
      - '/Users/yandixuan/Applications/dockerData/mysql/data:/var/lib/mysql'
      - '/Users/yandixuan/Applications/dockerData/mysql/conf:/etc/mysql/conf.d'

networks:
  default:
    external:
      name: ydx

