version: '3.8'

services:
  mysql8.0:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    restart: 'always'
    container_name: mysql8.0
    volumes:
      - 'D:/docker-data/mysql-8.0/data:/var/lib/mysql'

  mysql5.7:
    image: mysql:5.7
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 'root'
    restart: 'always'
    container_name: mysql5.7
    volumes:
      - 'D:/docker-data/mysql-5.7/data:/var/lib/mysql'
